### ISSUE TITLE
20-06-17/responsive/index.html : méthofde de redirection non futurte proof

### ISSUE THREAD

**Issue by jibundeyare** [Thomas-Ringot/popschool#2]
Il est tout à fait possible que dans 6 mois un nouvel OS apparaisse et que ton système de redirection à base de user-agent ne soit pas valide.

Cette méthode de redirection n'est donc pas recommandée à moins que désire ignorer les problèmes de compatible avec de potentiels future nouveaux appareils.

Enfin, si tu désire néanmoins utiliser cette technique, c'est du côté serveur qu'il faudra la mettre en place, cela évitera au client de télécharger une page pour rien avant d'être redirigé ailleurs.

**Comment by Thomas-Ringot** [comment]
Yes d'accord avec toi, le code venait de Philippe qui l'avais mis dans un cour pour nous montrer que c'était possible.
